-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/HitCounters/sql/hit_counter.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE hit_counter (
  page_id SERIAL NOT NULL,
  page_counter BIGINT DEFAULT 0 NOT NULL,
  PRIMARY KEY(page_id)
);

CREATE INDEX page_counter ON hit_counter (page_counter);
