-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/HitCounters/sql/hit_counter_extension.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/hit_counter_extension (hc_id INTEGER UNSIGNED NOT NULL);
