-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/HitCounters/sql/hit_counter.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/hit_counter (
  page_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  page_counter BIGINT UNSIGNED DEFAULT 0 NOT NULL,
  INDEX page_counter (page_counter),
  PRIMARY KEY(page_id)
) /*$wgDBTableOptions*/;
